name: firebase_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: 2.21.0
  firebase_auth: 4.12.0
  cloud_firestore: 4.12.2
  convex_bottom_bar: 3.2.0
  intl: 0.18.1
  firebase_storage: 11.4.1
  fluttertoast: 8.2.2
  nb_utils: 6.0.6
  image_picker: 1.0.4
  dropdown_search: 5.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/iconLogin.png
    - assets/images/bgProfile.png
    - assets/images/avatar.png
    - assets/images/iconBox.png
    - assets/images/formIcon (2).png
    - assets/images/formIcon.png
    - assets/images/avatarCewe.png
    - assets/images/avatarCowo.png
  uses-material-design: true

